import { post } from 'aws-amplify/api';
import { ensureAwsCredentials, readJsonPayload } from './amplifyRest';

const API_NAME = 'apiGet';
const LOCAL_GEMINI_KEY = process.env.REACT_APP_GEMINI_API_KEY || '';
const GEMINI_MODEL = process.env.REACT_APP_GEMINI_MODEL || 'gemini-2.0-flash';

const REPORT_TEMPLATE_INSTRUCTIONS = `You are an agricultural analytics assistant for BeaconHill, a farm monitoring platform.
You will receive a JSON object with farm metadata, soil sensor metrics, and ambient weather metrics for a specific time period.

You MUST produce a report that follows this EXACT structure. Output PDF-ready content: markdown tables + the HTML header block shown below. Do NOT wrap your output in markdown code fences. Do NOT add any preamble or postamble outside of the structure.

REQUIRED OUTPUT STRUCTURE:

<div style="display: flex; align-items: flex-start; gap: 2rem;">
  <img src="/img/BeaconHill.png" alt="Farm Analytics Visualization" width="200"/>
  <div style="display: flex; flex-direction: column; justify-content: center; gap: 0.5rem;">
    <div><strong>Farm Name:</strong> [farm name from data]</div>
    <div><strong>Report Time:</strong> [will be injected server-side]</div>
    <div><strong>Model Used:</strong> [will be injected server-side]</div>
  </div>
</div>

## [Farm Name] Metadata

| Field | Value |
|---|---|
| Farm Name | [from data] |
| Farm ID | [from data] |
| Location / Region | [from data] |
| Reporting Period | [from data] |
| Nodes | [list node count and names from data] |

## Soil Health

> Plain-language summary: [2-3 sentence farmer-friendly summary of overall soil health based on ALL the sensor data provided]

## Metrics

| Category | Classification | Confidence / Evidence |
|---|---|---|
| Health Status | [overall classification: Excellent/Good/Fair/Poor] | [brief evidence statement] |

| Soil Metric | Latest Reading | Condition Classification | Why this matters (farmer-friendly) | Concern Level | What to do / monitor |
|---|---:|---|---|---|---|
[One row per soil metric from the data. Use the metric label, latest value + unit, classify condition, explain in plain language, assign concern level (Low/Medium/High), and give actionable advice.]

| Ambient Metric | Condition Classification | Why this matters (farmer-friendly) | Concern Level | What to do / monitor |
|---|---:|---|---|---|
[One row per ambient metric from the data.]

### What's Going Well (If applicable)

| Positive Signal | Evidence (from readings) | Simple explanation |
|---|---|---|
[1-3 rows of positive observations from the data]

### What Needs Attention (If applicable)

| Concern | Evidence (from readings) | Why it's a problem | Suggested next steps |
|---|---|---|---|
[1-3 rows of concerns based on the data]

### Weekly Forecast

| Ambient Metric | Latest Value | Next Week's Projection | Potential Farm impact (plain language) |
|---|---:|---|---|
[One row per ambient metric with trend projection and farm impact]

## 4. Concerns & Plan of Action

### Top Concerns (Ranked)

1. **[Top concern title]**
   - Why it matters: [explanation]
   - Evidence: [from readings]
   - Immediate action (today/this week): [specific advice]
   - Ongoing monitoring: [what to watch]
2. **[Second concern title]**
   - Why it matters: [explanation]
   - Evidence: [from readings]
   - Immediate action (today/this week): [specific advice]
   - Ongoing monitoring: [what to watch]

### Recommended Monitoring Checklist

| Item | Frequency | Target | What "good" looks like |
|---|---|---|---|
[2-4 actionable checklist items]

### Final Farmer-Friendly Recommendation

[1-2 paragraph plain-language recommendation summarizing what the farmer should focus on this period]

---
*Report generated by BeaconHill Analytics. Not a substitute for professional agronomy advice.*

IMPORTANT RULES:
- Use ONLY the data provided. Do not invent readings.
- Keep language simple and farmer-friendly.
- Be specific: reference actual values from the data.
- The crop type matters: tailor thresholds and advice to the specific crop.
- Output raw markdown + the HTML header div. No code fences. No extra text outside the structure.`;

function summarizeTrend(trend) {
  if (!Array.isArray(trend) || !trend.length) return { latest: null, min: null, max: null, avg: null };
  const values = trend.map((p) => p.y).filter((v) => typeof v === 'number');
  if (!values.length) return { latest: null, min: null, max: null, avg: null };
  return {
    latest: values[values.length - 1],
    min: Math.min(...values),
    max: Math.max(...values),
    avg: +(values.reduce((s, v) => s + v, 0) / values.length).toFixed(2),
  };
}

function buildSummaryData(payload) {
  const summaryData = {
    viewMode: payload.viewMode,
    reportingPeriod: payload.reportingPeriod,
    farm: payload.farm,
    nodes: payload.nodes,
    farmMetrics: {},
    ambientMetrics: {},
  };
  if (payload.farmMetrics) {
    for (const [key, metricData] of Object.entries(payload.farmMetrics)) {
      summaryData.farmMetrics[key] = {
        label: metricData.label,
        unit: metricData.unit,
        summary: summarizeTrend(metricData.trend),
      };
    }
  }
  if (payload.ambientMetrics) {
    for (const [key, metricData] of Object.entries(payload.ambientMetrics)) {
      summaryData.ambientMetrics[key] = {
        label: metricData.label,
        unit: metricData.unit,
        summary: summarizeTrend(metricData.trend),
      };
    }
  }
  return summaryData;
}

function injectMetadata(reportContent, model) {
  const now = new Date().toLocaleString('en-US', {
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', hour12: true,
  });
  return reportContent
    .replace(/\[will be injected server-side\]/g, '')
    .replace('<strong>Report Time:</strong>', `<strong>Report Time:</strong> ${now}`)
    .replace('<strong>Model Used:</strong>', `<strong>Model Used:</strong> ${model}`);
}

/**
 * Call Gemini directly from the browser (local dev only).
 */
async function callGeminiDirect(payload) {
  const summaryData = buildSummaryData(payload);
  const userPrompt = `Here is the farm analytics data to analyze:\n\n${JSON.stringify(summaryData, null, 2)}`;
  const fullPrompt = `${REPORT_TEMPLATE_INSTRUCTIONS}\n\n${userPrompt}`;

  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${LOCAL_GEMINI_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: fullPrompt }] }],
        generationConfig: { temperature: 0.4, maxOutputTokens: 4096 },
      }),
    },
  );

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Gemini API returned ${res.status}: ${errText}`);
  }

  const parsed = await res.json();
  const text = parsed?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error('Gemini returned no text content');

  return {
    report: injectMetadata(text, GEMINI_MODEL),
    modelUsed: GEMINI_MODEL,
    generatedAt: new Date().toISOString(),
  };
}

/**
 * Request an AI-generated analytics report.
 * Uses direct Gemini call when REACT_APP_GEMINI_API_KEY is set (local dev),
 * otherwise routes through the Lambda via API Gateway (production).
 *
 * @param {Object} payload - built by buildAnalyticsReportPayload
 * @returns {Promise<{ report: string, modelUsed: string, generatedAt: string }>}
 */
export async function generateAnalyticsReport(payload) {
  if (LOCAL_GEMINI_KEY && LOCAL_GEMINI_KEY !== 'REPLACE_ME_WITH_YOUR_KEY') {
    return callGeminiDirect(payload);
  }

  await ensureAwsCredentials();
  const res = await post({
    apiName: API_NAME,
    path: '/analyticsReport',
    options: { body: payload },
  }).response;
  return readJsonPayload(res);
}
