const https = require('https');

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || '';
const GEMINI_MODEL = process.env.GEMINI_MODEL || 'gemini-2.0-flash';

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type,Authorization',
  'Access-Control-Allow-Methods': 'POST,OPTIONS',
};

function response(statusCode, body) {
  return {
    statusCode,
    headers: CORS_HEADERS,
    body: JSON.stringify(body),
  };
}

const REPORT_TEMPLATE_INSTRUCTIONS = `You are an agricultural analytics assistant for BeaconHill, a farm monitoring platform.
You will receive a JSON object with farm metadata, soil sensor metrics, and ambient weather metrics for a specific time period.

You MUST produce a report that follows this EXACT structure. Output PDF-ready content: markdown tables + the HTML header block shown below. Do NOT wrap your output in markdown code fences. Do NOT add any preamble or postamble outside of the structure.

REQUIRED OUTPUT STRUCTURE:

<div style="display: flex; align-items: flex-start; gap: 2rem;">
  <img src="/img/BeaconHill.png" alt="Farm Analytics Visualization" width="200"/>
  <div style="display: flex; flex-direction: column; justify-content: center; gap: 0.5rem;">
    <div><strong>Farm Name:</strong> [farm name from data]</div>
    <div><strong>Report Time:</strong> [will be injected server-side]</div>
    <div><strong>Model Used:</strong> [will be injected server-side]</div>
  </div>
</div>

## [Farm Name] Metadata

| Field | Value |
|---|---|
| Farm Name | [from data] |
| Farm ID | [from data] |
| Location / Region | [from data] |
| Reporting Period | [from data] |
| Nodes | [list node count and names from data] |

## Soil Health

> Plain-language summary: [2-3 sentence farmer-friendly summary of overall soil health based on ALL the sensor data provided]

## Metrics

| Category | Classification | Confidence / Evidence |
|---|---|---|
| Health Status | [overall classification: Excellent/Good/Fair/Poor] | [brief evidence statement] |

| Soil Metric | Latest Reading | Condition Classification | Why this matters (farmer-friendly) | Concern Level | What to do / monitor |
|---|---:|---|---|---|---|
[One row per soil metric from the data. Use the metric label, latest value + unit, classify condition, explain in plain language, assign concern level (Low/Medium/High), and give actionable advice.]

| Ambient Metric | Condition Classification | Why this matters (farmer-friendly) | Concern Level | What to do / monitor |
|---|---:|---|---|---|
[One row per ambient metric from the data.]

### What's Going Well (If applicable)

| Positive Signal | Evidence (from readings) | Simple explanation |
|---|---|---|
[1-3 rows of positive observations from the data]

### What Needs Attention (If applicable)

| Concern | Evidence (from readings) | Why it's a problem | Suggested next steps |
|---|---|---|---|
[1-3 rows of concerns based on the data]

### Weekly Forecast

| Ambient Metric | Latest Value | Next Week's Projection | Potential Farm impact (plain language) |
|---|---:|---|---|
[One row per ambient metric with trend projection and farm impact]

## 4. Concerns & Plan of Action

### Top Concerns (Ranked)

1. **[Top concern title]**
   - Why it matters: [explanation]
   - Evidence: [from readings]
   - Immediate action (today/this week): [specific advice]
   - Ongoing monitoring: [what to watch]
2. **[Second concern title]**
   - Why it matters: [explanation]
   - Evidence: [from readings]
   - Immediate action (today/this week): [specific advice]
   - Ongoing monitoring: [what to watch]

### Recommended Monitoring Checklist

| Item | Frequency | Target | What "good" looks like |
|---|---|---|---|
[2-4 actionable checklist items]

### Final Farmer-Friendly Recommendation

[1-2 paragraph plain-language recommendation summarizing what the farmer should focus on this period]

---
*Report generated by BeaconHill Analytics. Not a substitute for professional agronomy advice.*

IMPORTANT RULES:
- Use ONLY the data provided. Do not invent readings.
- Keep language simple and farmer-friendly.
- Be specific: reference actual values from the data.
- The crop type matters: tailor thresholds and advice to the specific crop.
- Output raw markdown + the HTML header div. No code fences. No extra text outside the structure.`;

/**
 * Call the Gemini REST API directly via https to avoid bundling an SDK.
 * @param {string} prompt
 * @returns {Promise<string>}
 */
function callGemini(prompt) {
  return new Promise((resolve, reject) => {
    const payload = JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        temperature: 0.4,
        maxOutputTokens: 4096,
      },
    });

    const options = {
      hostname: 'generativelanguage.googleapis.com',
      path: `/v1beta/models/${GEMINI_MODEL}:generateContent?key=${GEMINI_API_KEY}`,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(payload),
      },
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        if (res.statusCode !== 200) {
          reject(new Error(`Gemini API returned ${res.statusCode}: ${data}`));
          return;
        }
        try {
          const parsed = JSON.parse(data);
          const text = parsed?.candidates?.[0]?.content?.parts?.[0]?.text;
          if (!text) {
            reject(new Error('Gemini returned no text content'));
            return;
          }
          resolve(text);
        } catch (e) {
          reject(new Error(`Failed to parse Gemini response: ${e.message}`));
        }
      });
    });

    req.on('error', reject);
    req.write(payload);
    req.end();
  });
}

/**
 * Summarize trend data into a compact object for the prompt.
 */
function summarizeTrend(trend) {
  if (!Array.isArray(trend) || !trend.length) return { latest: null, min: null, max: null, avg: null };
  const values = trend.map((p) => p.y).filter((v) => typeof v === 'number');
  if (!values.length) return { latest: null, min: null, max: null, avg: null };
  return {
    latest: values[values.length - 1],
    min: Math.min(...values),
    max: Math.max(...values),
    avg: +(values.reduce((s, v) => s + v, 0) / values.length).toFixed(2),
  };
}

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') {
    return response(200, {});
  }

  if (!GEMINI_API_KEY || GEMINI_API_KEY === 'REPLACE_ME') {
    return response(503, { error: 'Gemini API key is not configured.' });
  }

  if (event.httpMethod !== 'POST') {
    return response(405, { error: `Method ${event.httpMethod} not allowed` });
  }

  let body;
  try {
    body = typeof event.body === 'string' ? JSON.parse(event.body) : event.body;
  } catch {
    return response(400, { error: 'Invalid JSON body' });
  }

  if (!body || !body.farm || !body.viewMode) {
    return response(400, { error: 'Missing required fields: farm, viewMode' });
  }

  const summaryData = {
    viewMode: body.viewMode,
    reportingPeriod: body.reportingPeriod,
    farm: body.farm,
    nodes: body.nodes,
    farmMetrics: {},
    ambientMetrics: {},
  };

  if (body.farmMetrics) {
    for (const [key, metricData] of Object.entries(body.farmMetrics)) {
      summaryData.farmMetrics[key] = {
        label: metricData.label,
        unit: metricData.unit,
        summary: summarizeTrend(metricData.trend),
      };
    }
  }

  if (body.ambientMetrics) {
    for (const [key, metricData] of Object.entries(body.ambientMetrics)) {
      summaryData.ambientMetrics[key] = {
        label: metricData.label,
        unit: metricData.unit,
        summary: summarizeTrend(metricData.trend),
      };
    }
  }

  const userPrompt = `Here is the farm analytics data to analyze:\n\n${JSON.stringify(summaryData, null, 2)}`;
  const fullPrompt = `${REPORT_TEMPLATE_INSTRUCTIONS}\n\n${userPrompt}`;

  try {
    let reportContent = await callGemini(fullPrompt);

    const now = new Date().toLocaleString('en-US', {
      year: 'numeric', month: '2-digit', day: '2-digit',
      hour: '2-digit', minute: '2-digit', hour12: true,
    });

    reportContent = reportContent
      .replace(/\[will be injected server-side\]/g, '')
      .replace(
        '<strong>Report Time:</strong>',
        `<strong>Report Time:</strong> ${now}`,
      )
      .replace(
        '<strong>Model Used:</strong>',
        `<strong>Model Used:</strong> ${GEMINI_MODEL}`,
      );

    return response(200, {
      report: reportContent,
      modelUsed: GEMINI_MODEL,
      generatedAt: now,
    });
  } catch (err) {
    console.error('Gemini call failed:', err);
    return response(502, { error: 'Failed to generate report. Please try again.' });
  }
};
